import ScrollReveal from "@/components/ScrollReveal";
import ClayIcon, { type ClayIconName } from "@/components/ClayIcon";
import MascotImage from "@/components/MascotImage";
import { useLanguage } from "@/contexts/LanguageContext";

const steps: Array<[ClayIconName, string, "purple" | "pink" | "yellow" | "blue" | "orange" | "green"]> = [["coffee", "coffee", "orange"], ["code", "code", "purple"], ["bug", "bug", "pink"], ["search", "google", "blue"], ["book", "stackoverflow", "yellow"], ["copy", "copy", "purple"], ["bug", "anotherBug", "orange"], ["sparkle", "repeat", "pink"]];

const DeveloperLife = () => { const { t } = useLanguage(); return <section id="life" className="section-padding overflow-hidden bg-orange-50/70 dark:bg-orange-500/5"><div className="container-custom"><div className="grid items-center gap-12 lg:grid-cols-[.7fr_1.3fr]"><ScrollReveal animation="fade-left"><div className="mx-auto max-w-sm"><MascotImage alt="Rehan clay mascot enjoying coffee" className="aspect-square" /><p className="-mt-8 rounded-2xl bg-card p-4 text-center text-sm font-bold shadow-lg">{t("life.mascotReaction")}</p></div></ScrollReveal><div><ScrollReveal><span className="font-mono text-sm uppercase tracking-wider text-primary">{t("life.subtitle")}</span><h2 className="mt-2 flex items-center gap-3 text-4xl font-black tracking-tight md:text-5xl">{t("life.title")} <ClayIcon name="bug" tone="pink" className="h-12 w-12" /></h2><p className="mt-4 max-w-xl text-muted-foreground">{t("life.description")}</p></ScrollReveal><div className="mt-8 grid grid-cols-2 gap-4 sm:grid-cols-4">{steps.map(([icon, key, tone], index) => <ScrollReveal key={key} delay={index * 50}><div className="clay-tile relative h-full p-4 text-center"><ClayIcon name={icon} tone={tone} className="mx-auto mb-2 h-12 w-12" /><p className="text-xs font-semibold leading-snug">{t(`life.step.${key}`)}</p>{index < steps.length - 1 && <span className="absolute -right-3 top-1/2 z-10 hidden text-xl text-primary sm:block">→</span>}</div></ScrollReveal>)}</div></div></div></div></section>; };
export default DeveloperLife;
